Update to xplanet-1.0.4

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -308,7 +308,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB am__fastdepOBJC_TRUE am__fastdepOBJC_FALSE PERL CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS HAVE_LIBX11_TRUE HAVE_LIBX11_FALSE EGREP XSS_LIBS HAVE_LIBGIF_TRUE HAVE_LIBGIF_FALSE HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE HAVE_LIBPNG_TRUE HAVE_LIBPNG_FALSE HAVE_LIBPNM_TRUE HAVE_LIBPNM_FALSE HAVE_LIBTIFF_TRUE HAVE_LIBTIFF_FALSE GRAPHICS_LIBS FREETYPE_CONFIG FREETYPE_CFLAGS FREETYPE_LIBS HAVE_LIBFREETYPE_TRUE HAVE_LIBFREETYPE_FALSE PKG_CONFIG PANGOFT2_CFLAGS PANGOFT2_LIBS HAVE_LIBPANGOFT2_TRUE HAVE_LIBPANGOFT2_FALSE AQUA_LIBS OBJC OBJCFLAGS HAVE_AQUA_TRUE HAVE_AQUA_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os HAVE_CYGWIN_TRUE HAVE_CYGWIN_FALSE USE_AR_TRUE USE_AR_FALSE xplanet_ARFLAGS xplanet_LDFLAGS separator mapext LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE RANLIB ac_ct_RANLIB am__fastdepOBJC_TRUE am__fastdepOBJC_FALSE PERL CPP X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS HAVE_LIBX11_TRUE HAVE_LIBX11_FALSE EGREP XSS_LIBS HAVE_LIBGIF_TRUE HAVE_LIBGIF_FALSE HAVE_LIBJPEG_TRUE HAVE_LIBJPEG_FALSE HAVE_LIBPNG_TRUE HAVE_LIBPNG_FALSE HAVE_LIBPNM_TRUE HAVE_LIBPNM_FALSE HAVE_LIBTIFF_TRUE HAVE_LIBTIFF_FALSE GRAPHICS_LIBS FREETYPE_CONFIG FREETYPE_CFLAGS FREETYPE_LIBS HAVE_LIBFREETYPE_TRUE HAVE_LIBFREETYPE_FALSE PKG_CONFIG PANGOFT2_CFLAGS PANGOFT2_LIBS HAVE_LIBPANGOFT2_TRUE HAVE_LIBPANGOFT2_FALSE CSPICE_LIBS HAVE_CSPICE_TRUE HAVE_CSPICE_FALSE AQUA_LIBS OBJC OBJCFLAGS HAVE_AQUA_TRUE HAVE_AQUA_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os HAVE_CYGWIN_TRUE HAVE_CYGWIN_FALSE USE_AR_TRUE USE_AR_FALSE xplanet_ARFLAGS xplanet_LDFLAGS separator mapext LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -875,6 +875,7 @@ Optional Packages:
   --with-tiff             Enable TIFF support (YES)
   --with-freetype         Enable Freetype support for TrueType fonts (YES)
   --with-pango            Enable Pango (YES)
+  --with-cspice           Use JPL's SPICE toolkit (NO)
   --with-aqua             For Mac OS X Aqua (NO)
   --with-cygwin           check for Cygwin environment (YES)
   --with-map-extension=EXTENSION
@@ -1570,7 +1571,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=xplanet
- VERSION=1.0.3
+ VERSION=1.0.4
 
 
 cat >>confdefs.h <<_ACEOF
@@ -3247,15 +3248,6 @@ else
   am__fastdepOBJC_FALSE=
 fi
 
-
-# my functions
-#AC_ARG_WITH(gui, [  --with-gui              Build xplanet-gui as well as xplanet [yes]])
-
-#AC_FIND_SOCKLEN_T
-#AC_FIND_PTHREADS
-#AC_FIND_JAVA
-
-#AM_PROG_GCJ
 
 # Extract the first word of "perl", so it can be a program name with args.
 set dummy perl; ac_word=$2
@@ -7134,6 +7126,244 @@ fi
 
 
 
+# Check whether --with-cspice or --without-cspice was given.
+if test "${with_cspice+set}" = set; then
+  withval="$with_cspice"
+
+fi;
+
+have_cspice='no'
+if test "$with_cspice" = yes; then
+  have_cspice_h='no'
+  if test "${ac_cv_header_SpiceUsr_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for SpiceUsr.h" >&5
+echo $ECHO_N "checking for SpiceUsr.h... $ECHO_C" >&6
+if test "${ac_cv_header_SpiceUsr_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_SpiceUsr_h" >&5
+echo "${ECHO_T}$ac_cv_header_SpiceUsr_h" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking SpiceUsr.h usability" >&5
+echo $ECHO_N "checking SpiceUsr.h usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <SpiceUsr.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking SpiceUsr.h presence" >&5
+echo $ECHO_N "checking SpiceUsr.h presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <SpiceUsr.h>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc in
+  yes:no )
+    { echo "$as_me:$LINENO: WARNING: SpiceUsr.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: SpiceUsr.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SpiceUsr.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SpiceUsr.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+  no:yes )
+    { echo "$as_me:$LINENO: WARNING: SpiceUsr.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: SpiceUsr.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SpiceUsr.h: check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: SpiceUsr.h: check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: SpiceUsr.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: SpiceUsr.h: proceeding with the preprocessor's result" >&2;}
+    (
+      cat <<\_ASBOX
+## ------------------------------------ ##
+## Report this to bug-autoconf@gnu.org. ##
+## ------------------------------------ ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for SpiceUsr.h" >&5
+echo $ECHO_N "checking for SpiceUsr.h... $ECHO_C" >&6
+if test "${ac_cv_header_SpiceUsr_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_SpiceUsr_h=$ac_header_preproc
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_SpiceUsr_h" >&5
+echo "${ECHO_T}$ac_cv_header_SpiceUsr_h" >&6
+
+fi
+if test $ac_cv_header_SpiceUsr_h = yes; then
+  have_cspice_h='yes'
+else
+  have_cspice_h='no'
+fi
+
+
+  if test "$have_cspice_h" = 'yes'; then
+    have_cspice_lib='no'
+    echo "$as_me:$LINENO: checking for furnsh_c in -lcspice" >&5
+echo $ECHO_N "checking for furnsh_c in -lcspice... $ECHO_C" >&6
+if test "${ac_cv_lib_cspice_furnsh_c+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lcspice -lm $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char furnsh_c ();
+int
+main ()
+{
+furnsh_c ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_cspice_furnsh_c=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_cspice_furnsh_c=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_cspice_furnsh_c" >&5
+echo "${ECHO_T}$ac_cv_lib_cspice_furnsh_c" >&6
+if test $ac_cv_lib_cspice_furnsh_c = yes; then
+  have_cspice_lib='yes'
+else
+  have_cspice_lib='no'
+fi
+
+    if test "$have_cspice_lib" = 'yes'; then
+      CSPICE_LIBS="-lcspice"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CSPICE
+_ACEOF
+
+
+      have_cspice='yes'
+    fi
+  fi
+
+  if test "$have_cspice" = 'no'; then
+    { echo "$as_me:$LINENO: WARNING: *** Xplanet will be built without SPICE support ***" >&5
+echo "$as_me: WARNING: *** Xplanet will be built without SPICE support ***" >&2;}
+  fi
+fi
+
+
+
+if test "$have_cspice" = 'yes'; then
+  HAVE_CSPICE_TRUE=
+  HAVE_CSPICE_FALSE='#'
+else
+  HAVE_CSPICE_TRUE='#'
+  HAVE_CSPICE_FALSE=
+fi
+
+
+
+
 # Check whether --with-aqua or --without-aqua was given.
 if test "${with_aqua+set}" = set; then
   withval="$with_aqua"
@@ -7646,6 +7876,13 @@ if test -z "${HAVE_LIBPANGOFT2_TRUE}" && test -z "${HAVE_LIBPANGOFT2_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"HAVE_LIBPANGOFT2\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"HAVE_LIBPANGOFT2\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${HAVE_CSPICE_TRUE}" && test -z "${HAVE_CSPICE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"HAVE_CSPICE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"HAVE_CSPICE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -8290,6 +8527,9 @@ s,@PANGOFT2_CFLAGS@,$PANGOFT2_CFLAGS,;t t
 s,@PANGOFT2_LIBS@,$PANGOFT2_LIBS,;t t
 s,@HAVE_LIBPANGOFT2_TRUE@,$HAVE_LIBPANGOFT2_TRUE,;t t
 s,@HAVE_LIBPANGOFT2_FALSE@,$HAVE_LIBPANGOFT2_FALSE,;t t
+s,@CSPICE_LIBS@,$CSPICE_LIBS,;t t
+s,@HAVE_CSPICE_TRUE@,$HAVE_CSPICE_TRUE,;t t
+s,@HAVE_CSPICE_FALSE@,$HAVE_CSPICE_FALSE,;t t
 s,@AQUA_LIBS@,$AQUA_LIBS,;t t
 s,@OBJC@,$OBJC,;t t
 s,@OBJCFLAGS@,$OBJCFLAGS,;t t
